# Generated by Django 4.1.6 on 2023-02-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='image',
            field=models.ImageField(default='uploaded_images/default.jpg', upload_to='uploaded_images/'),
        ),
    ]
