# Generated by Django 4.1.6 on 2023-02-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_userprofile_alter_sell_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sell',
            name='image',
            field=models.ImageField(default='default.png', upload_to='uploaded_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
