# Generated by Django 4.1.6 on 2023-02-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_sell_id_alter_sell_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
